export const clerkAppearance = {
  baseTheme: undefined,
  variables: {
    colorPrimary: 'hsl(var(--primary))',
    colorBackground: 'hsl(var(--background))',
    colorInputBackground: 'hsl(var(--background))',
    colorInputText: 'hsl(var(--foreground))',
    colorText: 'hsl(var(--foreground))',
    colorTextSecondary: 'hsl(var(--muted-foreground))',
    borderRadius: '0.5rem',
  },
  elements: {
    formButtonPrimary: 'bg-primary hover:bg-primary/90 text-primary-foreground font-medium py-2 px-4 rounded-md transition-colors focus:ring-2 focus:ring-ring focus:ring-offset-2',
    card: 'shadow-lg border bg-card text-card-foreground',
    headerTitle: 'text-2xl font-bold text-foreground',
    headerSubtitle: 'text-muted-foreground',
    socialButtonsBlockButton: 'bg-secondary hover:bg-secondary/80 text-secondary-foreground border border-border',
    socialButtonsBlockButtonText: 'font-medium',
    formFieldLabel: 'text-sm font-medium text-foreground',
    formFieldInput: 'bg-background border border-input text-foreground placeholder:text-muted-foreground focus:ring-2 focus:ring-ring focus:ring-offset-2',
    footerActionLink: 'text-primary hover:text-primary/80 font-medium',
    dividerLine: 'bg-border',
    dividerText: 'text-muted-foreground',
    alert: 'border border-border bg-card text-card-foreground',
    alertText: 'text-sm',
    formFieldErrorText: 'text-sm text-destructive',
    otpCodeFieldInput: 'bg-background border border-input text-foreground focus:ring-2 focus:ring-ring focus:ring-offset-2',
    formResendCodeLink: 'text-primary hover:text-primary/80 font-medium',
    verificationLinkText: 'text-primary hover:text-primary/80',
    formFieldSuccessText: 'text-sm text-green-600',
  },
}